version: '3.8'

services:
  server:
    build: .
    container_name: gzacinema-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5000:5000'
    networks:
      - gzacinema-net
    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: gzacinema-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-gza_minio_user}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-gza_minio_pass}
    volumes:
      - /home/ubuntu/workspace/gzacinema/minio-data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - gzacinema-net

networks:
  gzacinema-net:
    external: true
